### ISSUE TITLE
Add a code action to add an unused rule to `pestIdeTools.alwaysUsedRuleNames`

### ISSUE THREAD

**Issue by Jamalam360** [pest-parser/pest-ide-tools#14]
I haven't yet found a way in the LSP for servers to update their own config, which may be annoying. I'll look more but this might have to be vs code exclusive.

**Comment by Jamalam360** [comment]
Yeah I don't believe the protocol supports this

**Comment by tomtau** [comment]
Maybe one heuristic could be not to display a warning if there is only one unused rule (that rule may likely be the root one)?

**Comment by Jamalam360** [comment]
That fix has been implemented in https://github.com/pest-parser/pest-ide-tools/commit/fa2d7bb42427f7ef5829ae249ef413be4275ef6e
