### ISSUE TITLE
Better `unused` warning

### ISSUE THREAD

**Issue by huacnlee** [pest-parser/pest-ide-tools#18]
<img width="737" alt="image" src="https://user-images.githubusercontent.com/5518/232367788-7fdc43c1-83d6-48cc-ab3c-2d8e09fa6343.png">

In a pest file, there will be always have a `grammar_rule` is not used. But that is the final rule, so the extension it will always show the `unused warning`.

**Comment by Jamalam360** [comment]
Duplicate of #14
