### ISSUE TITLE
Add GIFs?

### ISSUE THREAD

**Issue by bbkane** [pest-parser/pest-ide-tools#2]
I'd really love to see this plugin "in motion" from the README

**Comment by tomtau** [comment]
FYI @Jamalam360 shared a short video of the early version on Discord, I think it should be possible to convert it to GIFs and show them in README.
Or use this https://github.com/arciisine/vscode-chronicler ?

**Comment by Jamalam360** [comment]
Sure, I'll get some once I've finished the refractors to work with other editors

**Comment by Jamalam360** [comment]
https://github.com/pest-parser/pest-ide-tools/blob/feat/tower-lsp/README.md
