### ISSUE TITLE
Report errors generated by the grammar validator

### ISSUE THREAD

**Issue by Tartasprint** [pest-parser/pest-ide-tools#25]
## The problem

Consider the following grammar:

```pest
buggy = { (!"a")* }
```

It never consumes anything, and that error is caught by the validator in the [`pest_meta`](https://github.com/pest-parser/pest/blob/6355eaec4e71ed223f6f77c8095f52d7fea349b1/meta/src/validator.rs#L232) crate. The [playground](https://pest.rs/?g=eyJncmFtbWFyIjoiYnVnZ3kgPSB7ICghXCJhXCIpKiB9XG4iLCJpbnB1dCI6ImlmICJ9#editor)  and the debugger catch it, but the VSCode extension doesn't warn me.

## The requested feature

I would like to be warned by the VSCode extension about errors generated by the validator. It could be either that this is already done in the language server and the VSCode extension has a bug, or that it is not implemented in the language server. In the latter case it might be a good idea to implement this in the language server so that users of the other IDE extensions might benefit from it.

**Comment by Jamalam360** [comment]
Thank you, it seems we [call `validate_pairs`](https://github.com/pest-parser/pest-ide-tools/blob/main/language-server/src/lsp.rs#L583) but don't use some other methods like `validate_ast` so that is the problem

**Comment by Jamalam360** [comment]
Thank you for the report

@tomtau can you confirm that 

```rust
validator::validate_pairs(pairs.clone())?;
// This calls validator::validate_ast under the hood
parser::consume_rules(pairs)?;
```

would use all `pest_meta` analyses/features?

**Comment by tomtau** [comment]
yes, I think so
