### ISSUE TITLE
Parse Error indicator: off by one line

### ISSUE THREAD

**Issue by notpeter** [pest-parser/pest-ide-tools#37]
## **Describe the bug**

The red squiggly for Syntax Errors appears 1 line below where it should 

## **To Reproduce**

```
DCI = @{ DI ~ ":" LID }
DI = @{ "A" ~ ("."     ~ "B")* }
LID = { "a" }
```

Note the missing `~` on Line 1 after `":"`

## **Expected behavior**

Red squiggly line should be one line up, under the `LID` 

## **Screenshots**

<img width="800" alt="image" src="https://github.com/pest-parser/pest-ide-tools/assets/145113/65048fb0-6a16-4a01-b902-b0f30b4327cf">

## **Environment (please complete the following information):**

 - OS: MacOS
 - Editor: VSCode
 - Extension Version: v0.3.3 (also broken on main branch)

**Comment by Jamalam360** [comment]
Might be fixed locally if I remember correctly, I'll check when I next work on the LS
