### ISSUE TITLE
Aggressive matching of names for Built-In Rules (funky colors)

### ISSUE THREAD

**Issue by notpeter** [pest-parser/pest-ide-tools#38]
## **Describe the bug**

If you begin a rule name with the same characters as one of the built-in Rules, you get a half-highlighted identifier name.

## **To Reproduce**

```
ASCII_ALPHA_UNDERSCORE = { "_" | ASCII_ALPHA }
```

## **Expected behavior**

Only highlight in special shade (light blue in my theme) if the entire identifier matches.

## **Screenshots**

<img width="550" alt="image" src="https://github.com/pest-parser/pest-ide-tools/assets/145113/46427fbd-383d-41a4-a940-ad80c965fccb">

## **Environment (please complete the following information):**

 - OS: MacOS
 - Editor VSCode
 - Extension Version: 3.3.0 / development tip

**Comment by notpeter** [comment]
I may try to tackle this as my first contribution/PR.

**Comment by Jamalam360** [comment]
:+1:
