### ISSUE TITLE
not working with neovim when installed & managed with mason

### ISSUE THREAD

**Issue by jmwielandt** [pest-parser/pest-ide-tools#42]
## **Describe the bug**

LSP not working with neovim.
More info: https://github.com/williamboman/mason.nvim/issues/1503

 - Server Version [e.g. 0.2.0]: 0.3.6

**Comment by Jamalam360** [comment]
@jmwielandt please try installing https://github.com/pest-parser/pest.vim as well. There seems to be a section at the bottom of the README about using alongside Mason

**Comment by jmwielandt** [comment]
> @jmwielandt please try installing https://github.com/pest-parser/pest.vim as well. There seems to be a section at the bottom of the README about using alongside Mason

that was my workarround

**Comment by Jamalam360** [comment]
It's not really a workaround it's intended behaviour as far as I can see

**Comment by Jamalam360** [comment]
I'm presuming this is solved, please reopen if I've misunderstood
