### ISSUE TITLE
Extension does not function, runtime status lists `write after end`

### ISSUE THREAD

**Issue by rscarson** [pest-parser/pest-ide-tools#44]
## **Describe the bug**

Extension does not function, runtime status lists `write after end`

## **To Reproduce**

Install extension, confirm language server installed and functioning, configure location of language server, to to extension runtime status

## **Environment

 - Windows 10
 - vscode 1.84.2
 - PEST LS v0.3.6

**Comment by rscarson** [comment]
The issue was incompatibility with the extension `Pest Syntax Highlighter`,

removing that extension instantly corrected the problem with `pest-ide-tools`

**Comment by Jamalam360** [comment]
:+1:
