### ISSUE TITLE
Cannot format grammar rules while tags exist

### ISSUE THREAD

**Issue by Endericedragon** [pest-parser/pest-ide-tools#50]
## **Describe the bug**

The "Format Document" function of VS Code would have no effect when there are tags inside  the rules. The function immediately goes back to normal when I delete those tags.

## **To Reproduce**

1. Create an empty grammar file, let's say `grammar.pest`, and type in these rules:
    ```
    some_rule = { #tag = "test" ~ "rule" ~ "one" }
    another_rule_with_a_long_name = { "test" ~ "rule" ~ "two" ~ "with" ~ "a" ~ "long" ~ "name" }
    ```
3. Right click and select "Format Document", and you'll find that the file remain unchanged, even if the two equal signs `=` of the two rules are not aligned
4. Remove the tag in `some_rule`, so the content of `grammar.pest` is as follows:
    ```
    some_rule = { "test" ~ "rule" ~ "one" }
    another_rule_with_a_long_name = { "test" ~ "rule" ~ "two" ~ "with" ~ "a" ~ "long" ~ "name" }
    ```
3. Right click and select "Format Document", and now you'll find that the two equal signs `=` of the two rules has been aligned

### **Reproduction File**

The grammar rule file is described as above.

## **Expected behavior**

The "Format Document" functions normally, whether there are tags in my rules or not.

## **Screenshots**

![Code_8zVgXVTH9R](https://github.com/pest-parser/pest-ide-tools/assets/43962007/ce46d3ee-7a3a-473e-8f39-2f87a84e615a)

## **Environment (please complete the following information):**

 - OS: Windows 11 23H2
 - Editor: VS Code
 - Server Version:0.3.6

**Comment by Jamalam360** [comment]
I believe this is an issue with the pest-fmt crate

**Comment by Endericedragon** [comment]
> I believe this is an issue with the pest-fmt crate. I can't transfer issues on mobile GitHub though.

You're right. When running `pestfmt grammar.pest`, I received an error message, indicating that pestfmt cannot "recognize" those tags.

**Comment by huacnlee** [comment]
Yes, we need a new version.

I am waiting for update pest-site, that must update.

**Comment by Jamalam360** [comment]
I'll release a new IDE tools version when pest fmt is updated

**Comment by Endericedragon** [comment]
> I'll release a new IDE tools version when pest fmt is updated

The pestfmt has been bumped to 0.2.5. I look forward to the new tool version.

**Comment by Jamalam360** [comment]
I'm unable to update the extension right now; @tomtau it seems the VSCode publishing access token has expired. If you could update `VSCE_PAT` [here](https://github.com/pest-parser/pest-ide-tools/settings/secrets/actions) that would be great thanks :)
