### ISSUE TITLE
Release LSP server bin for macOS, Linux and Windows.

### ISSUE THREAD

**Issue by huacnlee** [pest-parser/pest-ide-tools#51]
Zed extension support integration LSP server, it can download LSP bin from GitHub Releases page.

So we need to let every release we have published bin in `tar.gz` archive to releases page.

The release file named can like this: `pest-${platform}-${arch}.tar.gz`

> The `arch` and `platform` part is required.

For example:

- pest-lsp-darwin-x86_64.tar.gz
- pest-lsp-darwin-x86_64.tar.gz
- pest-lsp-linux-x86_64.tar.gz
- pest-lsp-windows-x86_64.tar.gz

**Comment by Jamalam360** [comment]
I'll modify the release workflow to do this at some point this week

**Comment by Jamalam360** [comment]
It took a bit of experimentation, but I have a GitHub workflow that does this now. It could do with testing - I only have an x86 Linux and Windows machine, so I can't test anything else - help would be appreciated.

## Tests

Test by un-taring the file and running the `pest-language-server` binary. Type a random string like `pest` follow by a new line, you should get an error message from the server (which is good in this case).

- [ ] [darwin-aarch64](https://github.com/Jamalam360/pest-ide-tools-ci-test/releases/download/v30.test/pest-language-server-darwin-aarch64.tar.gz)
- [ ] [darwin-x86_64](https://github.com/Jamalam360/pest-ide-tools-ci-test/releases/download/v30.test/pest-language-server-darwin-x86_64.tar.gz)
- [ ] [linux-aarch64](https://github.com/Jamalam360/pest-ide-tools-ci-test/releases/download/v30.test/pest-language-server-linux-aarch64.tar.gz)
- [x] [linux-x86_64](https://github.com/Jamalam360/pest-ide-tools-ci-test/releases/download/v30.test/pest-language-server-linux-x86_64.tar.gz)
- [ ] [windows-x86_64](https://github.com/Jamalam360/pest-ide-tools-ci-test/releases/download/v30.test/pest-language-server-windows-x86_64.tar.gz)

---

@huacnlee I wasn't able to find any documentation from Zed about this, so please let me know if there is a problem with the naming format or anything else.

**Comment by huacnlee** [comment]
I will this that releases. It's looks ok.

**Comment by huacnlee** [comment]
I have done tests. You can release now.

**Comment by Jamalam360** [comment]
Sure will not be long just having lunch
