### ISSUE TITLE
Warning in unused rule

### ISSUE THREAD

**Issue by TheAwiteb** [pest-parser/pest-ide-tools#6]
I think it would be useful, to see which rules are not used

**Comment by Jamalam360** [comment]
Hmm, how do we want to handle rules that will never be used in the grammar itself, e.g. a root rule:

```pest
root = { SOI ~ statement+ ~ EOI }
statement = { ... } 
```

`root` will show up as unused as there are no references to it in the grammar. Thoughts?

**Comment by TheAwiteb** [comment]
I think we should recognize the root in some way. Is it possible to show the warning and the user can ignore the warning of a certain rule? Therefore, the warning will not appear again

**Comment by Jamalam360** [comment]
For now I have added a configuration option to ignore rules with certain names, although I may revisit this in the future

**Comment by TheAwiteb** [comment]
> For now I have added a configuration option to ignore rules with certain names

Nice idea, so if someone wants to ignore another thing he just need to add it to the list

**Comment by TheAwiteb** [comment]
Thank you for your work 🤍🦀
