### ISSUE TITLE
View the doc of a rule

### ISSUE THREAD

**Issue by TheAwiteb** [pest-parser/pest-ide-tools#7]
The Pest parser [support] to document a rule, so let's show it 🚀 

[support]: https://github.com/pest-parser/pest-fmt/blob/master/src/grammar.pest#LL213-L214C50

**Comment by Jamalam360** [comment]
Thank you for both of your issues, I will get to them once I have finished our current rewrite (if that goes ahead :see_no_evil:)

**Comment by Jamalam360** [comment]
I have this working locally

**Comment by TheAwiteb** [comment]
> I have this working locally


https://user-images.githubusercontent.com/59842932/224562283-33d79cb6-4749-4438-a0c5-f99602aaaf3b.mov

It doesn't work well, I think it should work when the cursor is placed on it and not when ctrl is pressed. It works fine with biltin rules

**Comment by Jamalam360** [comment]
Wait huh? I think that's something your IDE is doing automatically, since my work hasn't even been pushed to GitHub let alone published to the extension. Am I getting confused?

**Comment by TheAwiteb** [comment]
> Wait huh? I think that's something your IDE is doing automatically, since my work hasn't even been pushed to GitHub let alone published to the extension. Am I getting confused?

I really don't know, it appears to me that the latest update was soon, this means that the same code in the repository is the same as the extension
```
Published
3/4/2023, 22:16:29
Last released
3/6/2023, 23:20:39
Last updated
3/11/2023, 08:36:39
Identifier
pest.pest-ide-tools
```

**Comment by Jamalam360** [comment]
There's definitely nothing related to rule docs in the released code at the moment, so I'm going to say this is vscode being smart. I'll reply here when the next version is released that will include this properly

**Comment by TheAwiteb** [comment]
> so I'm going to say this is vscode being smart

lol 😆
