### ISSUE TITLE
[BUG] Goto Definition handler

### ISSUE THREAD

**Issue by miroslavbel** [pest-parser/pest-ide-tools#8]
It seems like there is a bug in [Goto Definition](https://github.com/pest-parser/pest-ide-tools/blob/3c59fc41e0b8a4b6138ff9e661be5aaaeea3a26d/language-server/src/lib.rs#L293) response.

Seems like it returns the result with a subtraction (with underflow) of `1` for all four fields.
For the example below:
| symbol  | expected  | lsp response    |
|---------|-----------|-----------------|
| `first` | `0:0-0:5` | `MAX:MAX-NAX:4` |
| `x`     | `3:0-3:1` | `  2:MAX-  2:0` |
| `y`     | `5:4-5:5` | `  4:3  -  4:4` |

, where `MAX` stands for `u32::MAX`

The example:
```
first = { ANY }

// some comment
x = { first }

    y = { x } // there are 4 spaces before this symbol

```

I noticed this commit ([b503d1b](https://github.com/pest-parser/pest-ide-tools/commit/b503d1bbea99c28207606539bd8cde83697be545)) where a subtraction of one was added for both enum invariant (`Pos` and `Span`). It seems to work well when I delete this subtraction for `Span` (but not for `Pos`, as this make the wrong reponse for diagnostics).

**Comment by Jamalam360** [comment]
I think this is fixed locally on my machine, I'll check

**Comment by miroslavbel** [comment]
I think the problem is that there is double `- 1`:
1. [here](https://github.com/pest-parser/pest-ide-tools/blob/3c59fc41e0b8a4b6138ff9e661be5aaaeea3a26d/language-server/src/helpers.rs#L55), when casting pest's line_col (which is one-based) to pest's `LineColLocation::Span`
2. [here](https://github.com/pest-parser/pest-ide-tools/blob/3c59fc41e0b8a4b6138ff9e661be5aaaeea3a26d/language-server/src/helpers.rs#L44-L45), when casting pest's `LineColLocation::Span` to lsp's `Range` (which is zero-based)

But in any case, it's strange if only I have this issue
